services:
  - type: web
    name: gestiondestock
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app_deploy.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16
