services:
  - type: web
    name: boutique-mobile
    env: python
    runtime: python-3.10.12
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app_minimal:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.12
